# Generated by Django 3.2.4 on 2021-06-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DzienTygodnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mityng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_telefonu', models.CharField(max_length=20)),
                ('pin', models.CharField(blank=True, max_length=10)),
                ('godzina', models.PositiveSmallIntegerField()),
                ('minuta', models.PositiveSmallIntegerField()),
                ('dzien_tygodnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mityngi.dzientygodnia')),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mityngi.miasto')),
            ],
        ),
    ]
